from services.alignment import align_sequences
from services.fasta_generation import generate_fasta
from services.frequencies import calculate_frequencies
from services.sequence_search import sequence_search