"""empty message

Revision ID: 2bf50ec1f8d6
Revises: 
Create Date: 2026-03-16 16:50:19.283731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf50ec1f8d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunediscoverdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.String(length=30), nullable=False),
    sa.Column('case', sa.String(length=30), nullable=False),
    sa.Column('db_name', sa.String(length=20), nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=False),
    sa.Column('allele', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('flank_index', sa.Integer(), nullable=False),
    sa.Column('IgSNPer_uncommon', sa.Float(), nullable=True),
    sa.Column('IgSNPer_SNPs', sa.String(length=80), nullable=True),
    sa.Column('db_name_AA', sa.String(length=20), nullable=True),
    sa.Column('db_name_AA_list', sa.String(length=80), nullable=True),
    sa.Column('sequence_AA', sa.String(length=80), nullable=True),
    sa.Column('superpopulation', sa.String(length=20), nullable=False),
    sa.Column('population', sa.String(length=20), nullable=False),
    sa.Column('loaded_from_tsv', sa.String(length=80), nullable=False),
    sa.Column('loaded_at', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case', 'db_name', 'gene', 'flank_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunediscoverdata')
    # ### end Alembic commands ###
