"""empty message

Revision ID: 87c3fa2a3c33
Revises: 
Create Date: 2024-07-08 19:24:04.088119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c3fa2a3c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunediscoverdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.String(length=30), nullable=False),
    sa.Column('case', sa.String(length=30), nullable=False),
    sa.Column('db_name', sa.String(length=20), nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('prefix', sa.String(length=30), nullable=True),
    sa.Column('heptamer', sa.String(length=10), nullable=True),
    sa.Column('pre_heptamer', sa.String(length=10), nullable=True),
    sa.Column('post_heptamer', sa.String(length=10), nullable=True),
    sa.Column('suffix', sa.String(length=30), nullable=True),
    sa.Column('flank_index', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('full_count', sa.Integer(), nullable=True),
    sa.Column('superpopulation', sa.String(length=20), nullable=False),
    sa.Column('population', sa.String(length=20), nullable=False),
    sa.Column('loaded_from_tsv', sa.String(length=80), nullable=False),
    sa.Column('loaded_at', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case', 'db_name', 'flank_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunediscoverdata')
    # ### end Alembic commands ###
