"""empty message

Revision ID: a673481fc053
Revises: 
Create Date: 2024-06-04 15:13:19.444749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a673481fc053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunediscoverdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well', sa.Integer(), nullable=True),
    sa.Column('case', sa.String(length=30), nullable=False),
    sa.Column('db_name', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('heptamer', sa.String(length=10), nullable=True),
    sa.Column('prefix', sa.String(length=30), nullable=True),
    sa.Column('full_count', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=False),
    sa.Column('full_frequency', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('flank_index', sa.Integer(), nullable=True),
    sa.Column('log2_count', sa.Float(), nullable=True),
    sa.Column('file', sa.String(length=80), nullable=True),
    sa.Column('loaded_from_tsv', sa.String(length=80), nullable=False),
    sa.Column('loaded_at', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunediscoverdata')
    # ### end Alembic commands ###
